---
name: build
on: [push, workflow_dispatch]
jobs:
  build-java-source:
    name: build app and image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java build environmant
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Upload jar file
        uses: actions/upload-artifact@v3
        with:
          name: javademo.jar
          path: target/javademo.jar

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gchr.io/${{ github.repository }}:latest
