---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        type: string
        required: true
      development_version:
        description: Next version to set in pom.xml after release. Suffix "-SNAPSHOT" is added automatically.
        type: string
        required: true

jobs:
  maven-release:
    name: Release with Maven
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java build environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # TODO: use output from this step to create GitHub release
      - name: Update CHANGELOG.md
        id: update_changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v3
        with:
          tag: ${{ inputs.version }}

      - name: Commit CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "Add version ${{ inputs.version }} to CHANGELOG.md"

      - name: Prepare Maven release
        run: |
          mvn -B \
            -Darguments=-DskipTests \
            -DreleaseVersion=${{ inputs.version }} \
            -DdevelopmentVersion=${{ inputs.development_version }}-SNAPSHOT \
            -Dusername=${{ github.actor }} \
            -Dpassword=${{ secrets.GITHUB_TOKEN }} \
            release:prepare

      - name: Run build workflow
        run: |
          gh workflow run build.yaml
        env:
          GH_TOKEN: ${{ github.token }}
