---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        type: string
        required: true
      development_version:
        description: Next version to set in pom.xml after release. Suffix "-SNAPSHOT" is added automatically.
        type: string
        required: true

jobs:
  maven-release:
    name: Release with Maven
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java build environment
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Run Maven release plugin
        run: |
          mvn -B \
            -DskipTests \
            -DreleaseVersion=${{ inputs.version }} \
            -DdevelopmentVersion=${{ inputs.development_version }}-SNAPSHOT \
            release:prepare
          mvn release:perform
